server:
  port: 8081

message: Chao mung den patient service tu Config server

app:
  welcome: Chao mung den patient service tu Config server

spring:
  application:
    name: doctor-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    url: jdbc:postgresql://localhost:5432/doctor_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
